const hazmatNFPA400 = [
  {
    "nameHe": "מימן נוזלי",
    "nameEn": "Liquid Hydrogen",
    "formula": "H₂",
    "cas": "1333-74-0",
    "un": "1966",
    "dot": "2.1",
    "fp": "גז",
    "bp": "-253",
    "lel": "4",
    "uel": "75",
    "ait": "500",
    "catHe": "גזים דליקים קריוגניים",
    "cat": "Flammable Gas",
    "cls": "4",
    "clsLbl": "סיווג 4",
    "cat2": "גזים דליקים",
    "h": "0",
    "f": "4",
    "r": "3",
    "sp": "CRYO",
    "cc": "nc-flam",
    "note": "קריוגני"
  },
  {
    "nameHe": "נתרן",
    "nameEn": "Sodium",
    "formula": "Na",
    "cas": "7440-23-5",
    "un": "1428",
    "dot": "4.3",
    "fp": "לא רלוונטי",
    "bp": "883",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים רגישים למים",
    "cat": "Water-Reactive",
    "cls": "3",
    "clsLbl": "סיווג 3",
    "cat2": "פירוטכניקה",
    "h": "3",
    "f": "1",
    "r": "3",
    "sp": "W",
    "cc": "nc-wat",
    "note": "מתלקח במים"
  },
  {
    "nameHe": "חמצן נוזלי",
    "nameEn": "Liquid Oxygen",
    "formula": "O₂",
    "cas": "7782-44-7",
    "un": "1073",
    "dot": "2.2",
    "fp": "לא דליק",
    "bp": "-183",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים קריוגניים",
    "cat": "Oxidizer",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "0",
    "f": "0",
    "r": "0",
    "sp": "OX CRYO",
    "cc": "nc-ox",
    "note": "מחמצן+קריוגני"
  },
  {
    "nameHe": "חומצה גופרתית 98%",
    "nameEn": "Sulfuric Acid 98%",
    "formula": "H₂SO₄",
    "cas": "7664-93-9",
    "un": "1830",
    "dot": "8",
    "fp": "לא דליק",
    "bp": "337",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "חומצה חזקה",
    "cat2": "מחמצנים קורוזיביים",
    "h": "3",
    "f": "0",
    "r": "2",
    "sp": "W OX",
    "cc": "nc-corr",
    "note": "קורוזיבי חזק"
  },
  {
    "nameHe": "אמוניה נוזלית",
    "nameEn": "Liquid Ammonia",
    "formula": "NH₃",
    "cas": "7664-41-7",
    "un": "1005",
    "dot": "2.3",
    "fp": "גז",
    "bp": "-33",
    "lel": "15",
    "uel": "28",
    "ait": "651",
    "catHe": "גזים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "גזים קורוזיביים",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "COR",
    "cc": "nc-tox",
    "note": "גז רעיל+קורוזיבי"
  },
  {
    "nameHe": "כלור",
    "nameEn": "Chlorine",
    "formula": "Cl₂",
    "cas": "7782-50-5",
    "un": "1017",
    "dot": "2.3",
    "fp": "גז",
    "bp": "-34",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "מחמצנים (גז)",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "OX COR",
    "cc": "nc-tox",
    "note": "מחמצן+רעיל"
  },
  {
    "nameHe": "פרופאן",
    "nameEn": "Propane",
    "formula": "C₃H₈",
    "cas": "74-98-6",
    "un": "1075",
    "dot": "2.1",
    "fp": "גז",
    "bp": "-42",
    "lel": "2.1",
    "uel": "9.5",
    "ait": "450",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": "LPG"
  },
  {
    "nameHe": "מימן פרוקסיד 35%",
    "nameEn": "Hydrogen Peroxide 35%",
    "formula": "H₂O₂",
    "cas": "7722-84-1",
    "un": "2015",
    "dot": "5.1",
    "fp": "לא דליק",
    "bp": "108",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "1",
    "sp": "OX",
    "cc": "nc-ox2",
    "note": "מחמצן חזק"
  },
  {
    "nameHe": "אצטילן",
    "nameEn": "Acetylene",
    "formula": "C₂H₂",
    "cas": "74-86-2",
    "un": "1001",
    "dot": "2.1",
    "fp": "גז",
    "bp": "גז",
    "lel": "2.5",
    "uel": "100",
    "ait": "305",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "חומרים לא יציבים Class 3",
    "h": "1",
    "f": "4",
    "r": "3",
    "sp": "",
    "cc": "nc-flam",
    "note": "לא יציב בלחץ"
  },
  {
    "nameHe": "נתרן מתכתי",
    "nameEn": "Sodium Metal",
    "formula": "Na",
    "cas": "7440-23-5",
    "un": "1428",
    "dot": "4.3",
    "fp": "לא דליק",
    "bp": "883",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים רגישים למים",
    "cat": "Water-Reactive",
    "cls": "3",
    "clsLbl": "סיווג 3",
    "cat2": "חומרים פירוטכניים",
    "h": "3",
    "f": "1",
    "r": "3",
    "sp": "W",
    "cc": "nc-wat",
    "note": "מתלקח במגע מים"
  },
  {
    "nameHe": "אתאן נוזלי (LNG)",
    "nameEn": "Liquid Ethane",
    "formula": "C₂H₆",
    "cas": "74-84-0",
    "un": "1961",
    "dot": "2.1",
    "fp": "גז",
    "bp": "-89",
    "lel": "3.0",
    "uel": "12.4",
    "ait": "472",
    "catHe": "גזים דליקים קריוגניים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "LP-Gas",
    "cat2": "גזים דליקים",
    "h": "1",
    "f": "4",
    "r": "0",
    "sp": "CRYO",
    "cc": "nc-flam",
    "note": "קריוגני דליק"
  },
  {
    "nameHe": "חומצה פוספורית 85%",
    "nameEn": "Phosphoric Acid 85%",
    "formula": "H₃PO₄",
    "cas": "7664-38-2",
    "un": "1805",
    "dot": "8",
    "fp": "לא דליק",
    "bp": "158",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "חומצה",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-corr",
    "note": "קורוזיבי"
  },
  {
    "nameHe": "חנקתי נתרן",
    "nameEn": "Sodium Nitrate",
    "formula": "NaNO₃",
    "cas": "7631-99-4",
    "un": "1498",
    "dot": "5.1",
    "fp": "לא דליק",
    "bp": "380",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "",
    "h": "1",
    "f": "0",
    "r": "1",
    "sp": "OX",
    "cc": "nc-ox2",
    "note": "מחמצן"
  },
  {
    "nameHe": "כלורי נתרן (אקונומיקה)",
    "nameEn": "Sodium Hypochlorite",
    "formula": "NaClO",
    "cas": "7681-52-9",
    "un": "1791",
    "dot": "8",
    "fp": "לא דליק",
    "bp": "מתפרק",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "1",
    "clsLbl": "סיווג 1",
    "cat2": "חומרים קורוזיביים",
    "h": "2",
    "f": "0",
    "r": "1",
    "sp": "OX COR",
    "cc": "nc-ox1",
    "note": "חיטוי מים"
  },
  {
    "nameHe": "TNT (טרי-ניטרו טולואן)",
    "nameEn": "Trinitrotoluene",
    "formula": "C₇H₅N₃O₆",
    "cas": "118-96-7",
    "un": "0209",
    "dot": "1.1D",
    "fp": "מוצק",
    "bp": "240",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרי נפץ",
    "cat": "Unstable (Reactive)",
    "cls": "",
    "clsLbl": "Division 1.1D",
    "cat2": "",
    "h": "2",
    "f": "4",
    "r": "4",
    "sp": "",
    "cc": "nc-unst",
    "note": "חומר נפץ"
  },
  {
    "nameHe": "חנקתי אמוניום",
    "nameEn": "Ammonium Nitrate",
    "formula": "NH₄NO₃",
    "cas": "6484-52-2",
    "un": "1942",
    "dot": "5.1",
    "fp": "מוצק",
    "bp": "210",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "1",
    "clsLbl": "סיווג 1",
    "cat2": "חומרי נפץ Class 2",
    "h": "1",
    "f": "0",
    "r": "3",
    "sp": "OX",
    "cc": "nc-ox1",
    "note": "דשן+נפץ"
  },
  {
    "nameHe": "איזו-בוטילן",
    "nameEn": "Isobutylene",
    "formula": "C₄H₈",
    "cas": "115-11-7",
    "un": "1055",
    "dot": "2.1",
    "fp": "גז",
    "bp": "-7",
    "lel": "1.8",
    "uel": "9.6",
    "ait": "465",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "1",
    "sp": "",
    "cc": "nc-flam",
    "note": "פולימרים"
  },
  {
    "nameHe": "פרופאדיאן",
    "nameEn": "Propadiene",
    "formula": "C₃H₄",
    "cas": "463-49-0",
    "un": "2200",
    "dot": "2.1",
    "fp": "גז",
    "bp": "-34",
    "lel": "2.5",
    "uel": "?",
    "ait": "?",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-flam",
    "note": "ריתוך"
  },
  {
    "nameHe": "מתיל-אצטילן",
    "nameEn": "Methylacetylene",
    "formula": "C₃H₄",
    "cas": "74-99-7",
    "un": "1060",
    "dot": "2.1",
    "fp": "גז",
    "bp": "-23",
    "lel": "1.7",
    "uel": "?",
    "ait": "?",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-flam",
    "note": "כימיקלים"
  },
  {
    "nameHe": "דימתיל אמין",
    "nameEn": "Dimethylamine",
    "formula": "C₂H₇N",
    "cas": "124-40-3",
    "un": "1032",
    "dot": "2.1",
    "fp": "גז",
    "bp": "-18",
    "lel": "2.8",
    "uel": "14.4",
    "ait": "400",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "גזים קורוזיביים",
    "h": "3",
    "f": "4",
    "r": "0",
    "sp": "COR",
    "cc": "nc-flam",
    "note": "ממס, תרופות"
  },
  {
    "nameHe": "פוסגן (קרבוניל כלוריד)",
    "nameEn": "Phosgene",
    "formula": "COCl₂",
    "cas": "75-44-5",
    "un": "1076",
    "dot": "2.3",
    "fp": "גז",
    "bp": "לא דליק",
    "lel": "8",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": "פוליקרבונט"
  },
  {
    "nameHe": "תחמוצת גופרית",
    "nameEn": "Sulfur Dioxide",
    "formula": "SO₂",
    "cas": "7446-09-5",
    "un": "1079",
    "dot": "2.3",
    "fp": "גז",
    "bp": "לא דליק",
    "lel": "-10",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "גזים קורוזיביים",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "COR",
    "cc": "nc-tox",
    "note": "חומצה גופרתית"
  },
  {
    "nameHe": "פרכלורט אשלגן",
    "nameEn": "Potassium Perchlorate",
    "formula": "KClO₄",
    "cas": "7778-74-7",
    "un": "1489",
    "dot": "5.1",
    "fp": "מוצק",
    "bp": "400",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "1",
    "clsLbl": "סיווג 1",
    "cat2": "",
    "h": "1",
    "f": "0",
    "r": "1",
    "sp": "OX",
    "cc": "nc-ox1",
    "note": "זיקוקים"
  },
  {
    "nameHe": "כלורט נתרן",
    "nameEn": "Sodium Chlorate",
    "formula": "NaClO₃",
    "cas": "7775-09-9",
    "un": "1495",
    "dot": "5.1",
    "fp": "מוצק",
    "bp": "300",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "",
    "h": "1",
    "f": "0",
    "r": "1",
    "sp": "OX",
    "cc": "nc-ox2",
    "note": "זיקוקים"
  },
  {
    "nameHe": "פרמנגנט אשלגן",
    "nameEn": "Potassium Permanganate",
    "formula": "KMnO₄",
    "cas": "7722-64-7",
    "un": "1490",
    "dot": "5.1",
    "fp": "מוצק",
    "bp": "מתפרק",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "",
    "h": "1",
    "f": "0",
    "r": "1",
    "sp": "OX",
    "cc": "nc-ox2",
    "note": "חיטוי, כימיה"
  },
  {
    "nameHe": "כרומט אשלגן",
    "nameEn": "Potassium Chromate",
    "formula": "K₂CrO₄",
    "cas": "7789-00-6",
    "un": "3288",
    "dot": "6.1",
    "fp": "מוצק",
    "bp": "מתפרק",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "מסרטן",
    "h": "3",
    "f": "0",
    "r": "1",
    "sp": "OX",
    "cc": "nc-ox2",
    "note": "חמצון, מסרטן"
  },
  {
    "nameHe": "סידן",
    "nameEn": "Calcium",
    "formula": "Ca",
    "cas": "7440-70-2",
    "un": "1401",
    "dot": "4.3",
    "fp": "מוצק",
    "bp": "842",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים רגישים למים",
    "cat": "Water-Reactive",
    "cls": "3",
    "clsLbl": "סיווג 3",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "2",
    "sp": "W",
    "cc": "nc-wat",
    "note": "מגיב עם מים"
  },
  {
    "nameHe": "מגנזיום (גושים)",
    "nameEn": "Magnesium",
    "formula": "Mg",
    "cas": "7439-95-4",
    "un": "1869",
    "dot": "4.1",
    "fp": "מוצק",
    "bp": "650",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים דליקים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "חומרים רגישים למים",
    "h": "1",
    "f": "1",
    "r": "1",
    "sp": "W",
    "cc": "nc-flam",
    "note": "סגסוגות"
  },
  {
    "nameHe": "ניטרוגליצרין",
    "nameEn": "Nitroglycerin",
    "formula": "C₃H₅N₃O₉",
    "cas": "55-63-0",
    "un": "0143",
    "dot": "1.1D",
    "fp": "נוזל",
    "bp": "13",
    "lel": "",
    "uel": "",
    "ait": "270",
    "catHe": "חומרי נפץ",
    "cat": "Unstable (Reactive)",
    "cls": "",
    "clsLbl": "Division 1.1D",
    "cat2": "",
    "h": "2",
    "f": "3",
    "r": "4",
    "sp": "",
    "cc": "nc-unst",
    "note": "חומר נפץ+רפואה"
  },
  {
    "nameHe": "פיקרית חומצה",
    "nameEn": "Picric Acid",
    "formula": "C₆H₃N₃O₇",
    "cas": "88-89-1",
    "un": "0154",
    "dot": "1.1D",
    "fp": "מוצק",
    "bp": "300",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרי נפץ",
    "cat": "Unstable (Reactive)",
    "cls": "",
    "clsLbl": "Division 1.1D",
    "cat2": "",
    "h": "3",
    "f": "4",
    "r": "4",
    "sp": "",
    "cc": "nc-unst",
    "note": "חומר נפץ"
  },
  {
    "nameHe": "אתיל מרקפטן",
    "nameEn": "Ethyl Mercaptan",
    "formula": "C₂H₆S",
    "cas": "75-08-1",
    "un": "2363",
    "dot": "3",
    "fp": "-48",
    "bp": "35",
    "lel": "2.8",
    "uel": "18.2",
    "ait": "299",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "4",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": "מריח גז"
  },
  {
    "nameHe": "טריפלואוריד בור",
    "nameEn": "Boron Trifluoride",
    "formula": "BF₃",
    "cas": "7637-07-2",
    "un": "1008",
    "dot": "2.3",
    "fp": "גז",
    "bp": "-100",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גז רעיל",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "קורוזיבי",
    "h": "4",
    "f": "0",
    "r": "0",
    "sp": "COR",
    "cc": "nc-tox",
    "note": "קטליזטור"
  },
  {
    "nameHe": "חומצה ברומית 48%",
    "nameEn": "Hydrobromic Acid 48%",
    "formula": "HBr",
    "cas": "10035-10-6",
    "un": "1788",
    "dot": "8",
    "fp": "לא דליק",
    "bp": "122",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "COR",
    "cc": "nc-corr",
    "note": "קורוזיבי חזק"
  },
  {
    "nameHe": "חומצה יודית",
    "nameEn": "Iodic Acid",
    "formula": "HIO₃",
    "cas": "7553-56-2",
    "un": "1744",
    "dot": "8",
    "fp": "מוצק",
    "bp": "מתפרק",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "4",
    "clsLbl": "סיווג 4",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "1",
    "sp": "OX",
    "cc": "nc-ox4",
    "note": "מחמצן חזק"
  },
  {
    "nameHe": "קוואטרניום-15 (פורמלדהיד)",
    "nameEn": "Quaternium-15",
    "formula": "C₁₃H₁₈ClN₂O₂",
    "cas": "4080-31-3",
    "un": "?",
    "dot": "",
    "fp": "מוצק",
    "bp": ">100",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים בעירים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "1",
    "r": "1",
    "sp": "",
    "cc": "nc-flam",
    "note": "משחרר פורמלדהיד"
  },
  {
    "nameHe": "נפתלן",
    "nameEn": "Naphthalene",
    "formula": "C₁₀H₈",
    "cas": "91-20-3",
    "un": "1334",
    "dot": "4.1",
    "fp": "79",
    "bp": "218",
    "lel": "0.9",
    "uel": "5.9",
    "ait": "526",
    "catHe": "מוצקים דליקים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "2",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": "כדורי נפתלין"
  },
  {
    "nameHe": "אנתרצן",
    "nameEn": "Anthracene",
    "formula": "C₁₄H₁₀",
    "cas": "120-12-7",
    "un": "?",
    "dot": "",
    "fp": "121",
    "bp": "340",
    "lel": "",
    "uel": "",
    "ait": "540",
    "catHe": "מוצקים דליקים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": "צבעים"
  },
  {
    "nameHe": "הידרוקינון",
    "nameEn": "Hydroquinone",
    "formula": "C₆H₆O₂",
    "cas": "123-31-9",
    "un": "2662",
    "dot": "6.1",
    "fp": "165",
    "bp": "287",
    "lel": "",
    "uel": "",
    "ait": "515",
    "catHe": "מוצקים בעירים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "מחמצן חלש",
    "h": "2",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": "צילום, נוגד חמצון"
  },
  {
    "nameHe": "גלוקוז",
    "nameEn": "Glucose",
    "formula": "C₆H₁₂O₆",
    "cas": "50-99-7",
    "un": "לא רלוונטי",
    "dot": "",
    "fp": "מוצק",
    "bp": "מתפרק",
    "lel": "",
    "uel": "",
    "ait": "400",
    "catHe": "אבק דליק",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": "מזון"
  },
  {
    "nameHe": "עמילן",
    "nameEn": "Starch",
    "formula": "(C₆H₁₀O₅)ₙ",
    "cas": "9005-25-8",
    "un": "לא רלוונטי",
    "dot": "",
    "fp": "מוצק",
    "bp": "מתפרק",
    "lel": "",
    "uel": "",
    "ait": "380",
    "catHe": "אבק דליק",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": "מזון"
  },
  {
    "nameHe": "חנקתי אמוניום",
    "nameEn": "Ammonium Nitrate",
    "formula": "NH₄NO₃",
    "cas": "6484-52-2",
    "un": "1942",
    "dot": "5.1",
    "fp": "מוצק",
    "bp": "170",
    "lel": "",
    "uel": "",
    "ait": "210",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "1",
    "clsLbl": "סיווג 1",
    "cat2": "חומר נפץ",
    "h": "1",
    "f": "0",
    "r": "3",
    "sp": "OX",
    "cc": "nc-ox1",
    "note": "דשן, ANFO"
  },
  {
    "nameHe": "יוד רדיואקטיבי I-131",
    "nameEn": "Iodine-131",
    "formula": "¹³¹I",
    "cas": "10043-66-0",
    "un": "2915",
    "dot": "7",
    "fp": "מוצק",
    "bp": "לא דליק",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומר רדיואקטיבי",
    "cat": "Radioactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "0",
    "sp": "RAD",
    "cc": "nc-other",
    "note": "רפואה גרעינית"
  },
  {
    "nameHe": "ונילין",
    "nameEn": "Vanillin",
    "formula": "C₈H₈O₃",
    "cas": "121-33-5",
    "un": "לא רלוונטי",
    "dot": "",
    "fp": "מוצק",
    "bp": "147",
    "lel": "",
    "uel": "",
    "ait": "285",
    "catHe": "מוצקים בעירים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": "טעם וריח"
  },
  {
    "nameHe": "tert-butyl hydroperoxide",
    "nameEn": "tert-Butyl Hydroperoxide",
    "formula": "C₄H₁₀O₂",
    "cas": "75-91-2",
    "un": "2093",
    "dot": "5.2",
    "fp": "27",
    "bp": "89",
    "lel": "",
    "uel": "",
    "ait": "200",
    "catHe": "פרוקסידים אורגניים",
    "cat": "Organic Peroxide",
    "cls": "III",
    "clsLbl": "סיווג III",
    "cat2": "נוזל דליק",
    "h": "3",
    "f": "3",
    "r": "3",
    "sp": "OX",
    "cc": "nc-op3",
    "note": "יוזם פולימריזציה"
  },
  {
    "nameHe": "lauroyl peroxide",
    "nameEn": "Lauroyl Peroxide",
    "formula": "C₂₄H₄₆O₄",
    "cas": "105-74-8",
    "un": "2124",
    "dot": "5.2",
    "fp": "100",
    "bp": "מתפרק",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פרוקסידים אורגניים",
    "cat": "Organic Peroxide",
    "cls": "II",
    "clsLbl": "סיווג II",
    "cat2": "",
    "h": "2",
    "f": "1",
    "r": "4",
    "sp": "OX",
    "cc": "nc-opii",
    "note": "פלסטיק"
  },
  {
    "nameHe": "peracetic acid 40%",
    "nameEn": "Peracetic Acid",
    "formula": "C₂H₄O₃",
    "cas": "79-21-0",
    "un": "3105",
    "dot": "5.2",
    "fp": "41",
    "bp": "105",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פרוקסידים אורגניים",
    "cat": "Organic Peroxide",
    "cls": "II",
    "clsLbl": "סיווג II",
    "cat2": "קורוזיבי",
    "h": "3",
    "f": "2",
    "r": "3",
    "sp": "OX COR",
    "cc": "nc-opii",
    "note": "חיטוי"
  },
  {
    "nameHe": "trimethylaluminum",
    "nameEn": "Trimethylaluminum",
    "formula": "C₃H₉Al",
    "cas": "75-24-1",
    "un": "3051",
    "dot": "4.2",
    "fp": "גז",
    "bp": "126",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזל פירוטכני",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "פירוטכני",
    "h": "4",
    "f": "4",
    "r": "3",
    "sp": "W",
    "cc": "nc-pyr",
    "note": "קטליזטור"
  },
  {
    "nameHe": "triethylaluminum",
    "nameEn": "Triethylaluminum",
    "formula": "C₆H₁₅Al",
    "cas": "97-93-8",
    "un": "3051",
    "dot": "4.2",
    "fp": "נוזל",
    "bp": "186",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזל פירוטכני",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "פירוטכני",
    "h": "4",
    "f": "4",
    "r": "3",
    "sp": "W",
    "cc": "nc-pyr",
    "note": "פולימרים"
  },
  {
    "nameHe": "n-butyllithium",
    "nameEn": "n-Butyllithium",
    "formula": "C₄H₉Li",
    "cas": "109-72-8",
    "un": "2445",
    "dot": "4.2",
    "fp": "נוזל",
    "bp": "80",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזל פירוטכני",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "פירוטכני+דליק",
    "h": "3",
    "f": "4",
    "r": "3",
    "sp": "W",
    "cc": "nc-pyr",
    "note": "ריאגנט"
  },
  {
    "nameHe": "diethylzinc",
    "nameEn": "Diethylzinc",
    "formula": "C₄H₁₀Zn",
    "cas": "557-20-0",
    "un": "3394",
    "dot": "4.2",
    "fp": "נוזל",
    "bp": "118",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזל פירוטכני",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "פירוטכני",
    "h": "4",
    "f": "4",
    "r": "3",
    "sp": "W",
    "cc": "nc-pyr",
    "note": "קטליזטור"
  },
  {
    "nameHe": "silane",
    "nameEn": "Silane",
    "formula": "SiH₄",
    "cas": "7803-62-5",
    "un": "2203",
    "dot": "2.1",
    "fp": "גז",
    "bp": "-112",
    "lel": "1.4",
    "uel": "98",
    "ait": "",
    "catHe": "גז דליק פירוטכני",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "פירוטכני",
    "h": "2",
    "f": "4",
    "r": "3",
    "sp": "",
    "cc": "nc-flam",
    "note": "מוליכים למחצה"
  },
  {
    "nameHe": "dichlorosilane",
    "nameEn": "Dichlorosilane",
    "formula": "H₂SiCl₂",
    "cas": "4109-96-0",
    "un": "2189",
    "dot": "2.3",
    "fp": "גז",
    "bp": "-70",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גז דליק",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "רגיש למים+קורוזיבי",
    "h": "3",
    "f": "4",
    "r": "2",
    "sp": "W COR",
    "cc": "nc-flam",
    "note": "סיליקון"
  },
  {
    "nameHe": "trichlorosilane",
    "nameEn": "Trichlorosilane",
    "formula": "HSiCl₃",
    "cas": "10025-78-2",
    "un": "1295",
    "dot": "4.3",
    "fp": "נוזל",
    "bp": "-50",
    "lel": "32",
    "uel": "",
    "ait": "",
    "catHe": "נוזל דליק",
    "cat": "Flammable Liquid",
    "cls": "IA",
    "clsLbl": "סיווג IA",
    "cat2": "רגיש למים+קורוזיבי",
    "h": "3",
    "f": "4",
    "r": "2",
    "sp": "W COR",
    "cc": "nc-flam",
    "note": "פוליסיליקון"
  },
  {
    "nameHe": "arsine",
    "nameEn": "Arsine",
    "formula": "AsH₃",
    "cas": "7784-42-1",
    "un": "2188",
    "dot": "2.3",
    "fp": "גז",
    "bp": "-62",
    "lel": "",
    "uel": "",
    "ait": "230",
    "catHe": "גז רעיל",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "גז רעיל מאוד",
    "h": "4",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-tox",
    "note": "מוליכים למחצה"
  },
  {
    "nameHe": "phosphine",
    "nameEn": "Phosphine",
    "formula": "PH₃",
    "cas": "7803-51-2",
    "un": "2199",
    "dot": "2.3",
    "fp": "גז",
    "bp": "-88",
    "lel": "",
    "uel": "",
    "ait": "100",
    "catHe": "גז דליק רעיל",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "רעיל+פירוטכני",
    "h": "4",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-flam",
    "note": "חיטוי"
  },
  {
    "nameHe": "stibine",
    "nameEn": "Stibine",
    "formula": "SbH₃",
    "cas": "7803-52-3",
    "un": "2676",
    "dot": "2.3",
    "fp": "גז",
    "bp": "-88",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גז רעיל דליק",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "רעיל מאוד",
    "h": "4",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-flam",
    "note": "מוליכים למחצה"
  },
  {
    "nameHe": "carbon nanotubes",
    "nameEn": "Carbon Nanotubes",
    "formula": "C",
    "cas": "משתנה",
    "un": "?",
    "dot": "",
    "fp": "מוצק",
    "bp": ">600",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצק דליק",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "סיכון נשימתי",
    "h": "2",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": "ננו-חומר"
  },
  {
    "nameHe": "sulfuryl fluoride",
    "nameEn": "Sulfuryl Fluoride",
    "formula": "SO₂F₂",
    "cas": "2699-79-8",
    "un": "2191",
    "dot": "2.3",
    "fp": "גז",
    "bp": "-55",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גז רעיל",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": "חיטוי מבנים"
  },
  {
    "nameHe": "פורמלדהיד 37%",
    "nameEn": "Formaldehyde 37%",
    "formula": "CH₂O",
    "cas": "50-00-0",
    "un": "1198",
    "dot": "",
    "fp": "56",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "2",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "חומצה הידרוכלורית 37%",
    "nameEn": "Hydrochloric Acid 37%",
    "formula": "HCl",
    "cas": "7647-01-0",
    "un": "1789",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "חומצה חנקתית 70%",
    "nameEn": "Nitric Acid 70%",
    "formula": "HNO₃",
    "cas": "7697-37-2",
    "un": "2031",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-ox",
    "note": ""
  },
  {
    "nameHe": "נתרן הידרוקסיד 50%",
    "nameEn": "Sodium Hydroxide 50%",
    "formula": "NaOH",
    "cas": "1310-73-2",
    "un": "1824",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "אמוניה 28%",
    "nameEn": "Ammonium Hydroxide 28%",
    "formula": "NH₄OH",
    "cas": "1336-21-6",
    "un": "2672",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "חומצה הידרופלואורית",
    "nameEn": "Hydrofluoric Acid",
    "formula": "HF",
    "cas": "7664-39-3",
    "un": "1790",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים רעילים מאוד",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "חומצה פרכלורית 70%",
    "nameEn": "Perchloric Acid 70%",
    "formula": "HClO₄",
    "cas": "7601-90-3",
    "un": "1802",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "4",
    "sp": "",
    "cc": "nc-ox",
    "note": ""
  },
  {
    "nameHe": "אשלגן הידרוקסיד",
    "nameEn": "Potassium Hydroxide",
    "formula": "KOH",
    "cas": "1310-58-3",
    "un": "1813",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "חומצה אוקסלית",
    "nameEn": "Oxalic Acid",
    "formula": "C₂H₂O₄",
    "cas": "144-62-7",
    "un": "3261",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "חומצה בנזואית",
    "nameEn": "Benzoic Acid",
    "formula": "C₇H₆O₂",
    "cas": "65-85-0",
    "un": "",
    "dot": "",
    "fp": "121",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים בעירים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "חומצה ציטרית",
    "nameEn": "Citric Acid",
    "formula": "C₆H₈O₇",
    "cas": "77-92-9",
    "un": "",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים קורוזיביים קלים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "פחמן חד-חמצני",
    "nameEn": "Carbon Monoxide",
    "formula": "CO",
    "cas": "630-08-0",
    "un": "1016",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "4",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "מימן כלורי",
    "nameEn": "Hydrogen Chloride",
    "formula": "HCl",
    "cas": "7647-01-0",
    "un": "1050",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "גופרית דו-חמצנית",
    "nameEn": "Sulfur Dioxide",
    "formula": "SO₂",
    "cas": "7446-09-5",
    "un": "1079",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "אתילן",
    "nameEn": "Ethylene",
    "formula": "C₂H₄",
    "cas": "74-85-1",
    "un": "1962",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "פרופילן",
    "nameEn": "Propylene",
    "formula": "C₃H₆",
    "cas": "115-07-1",
    "un": "1077",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "1",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "בוטאן",
    "nameEn": "Butane",
    "formula": "C₄H₁₀",
    "cas": "106-97-8",
    "un": "1011",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "מתאן",
    "nameEn": "Methane",
    "formula": "CH₄",
    "cas": "74-82-8",
    "un": "1971",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "פחמן טטרכלוריד",
    "nameEn": "Carbon Tetrachloride",
    "formula": "CCl₄",
    "cas": "56-23-5",
    "un": "1846",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "1,1,1-טריכלורואתאן",
    "nameEn": "1,1,1-Trichloroethane",
    "formula": "C₂H₃Cl₃",
    "cas": "71-55-6",
    "un": "2831",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "ברומומתאן",
    "nameEn": "Methyl Bromide",
    "formula": "CH₃Br",
    "cas": "74-83-9",
    "un": "1062",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "כלורומתאן",
    "nameEn": "Methyl Chloride",
    "formula": "CH₃Cl",
    "cas": "74-87-3",
    "un": "1063",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "4",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "דיברומומתאן",
    "nameEn": "Dibromomethane",
    "formula": "CH₂Br₂",
    "cas": "74-95-3",
    "un": "",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "אבץ אבקה",
    "nameEn": "Zinc Powder",
    "formula": "Zn",
    "cas": "7440-66-6",
    "un": "1436",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "3",
    "r": "2",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "אלומיניום אבקה",
    "nameEn": "Aluminum Powder",
    "formula": "Al",
    "cas": "7429-90-5",
    "un": "1309",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "3",
    "r": "2",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "מגנזיום אבקה",
    "nameEn": "Magnesium Powder",
    "formula": "Mg",
    "cas": "7439-95-4",
    "un": "1418",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "3",
    "r": "2",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "זרחן אדום",
    "nameEn": "Red Phosphorus",
    "formula": "P",
    "cas": "7723-14-0",
    "un": "1338",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים דליקים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "1",
    "r": "1",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "ליתיום מתכתי",
    "nameEn": "Lithium Metal",
    "formula": "Li",
    "cas": "7439-93-2",
    "un": "1415",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "2",
    "r": "2",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "אשלגן מתכתי",
    "nameEn": "Potassium Metal",
    "formula": "K",
    "cas": "7440-09-7",
    "un": "2257",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "3",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "סידן קרבידי",
    "nameEn": "Calcium Carbide",
    "formula": "CaC₂",
    "cas": "75-20-7",
    "un": "1402",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "3",
    "r": "2",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "סידן מתכתי",
    "nameEn": "Calcium Metal",
    "formula": "Ca",
    "cas": "7440-70-2",
    "un": "1401",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "3",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "נתרן היפוכלוריט",
    "nameEn": "Sodium Hypochlorite",
    "formula": "NaClO",
    "cas": "7681-52-9",
    "un": "1791",
    "dot": "",
    "fp": "לא דליק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox",
    "note": ""
  },
  {
    "nameHe": "אבקת ברזל",
    "nameEn": "Iron Powder",
    "formula": "Fe",
    "cas": "7439-89-6",
    "un": "1383",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים דליקים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "2",
    "r": "1",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "גופרית",
    "nameEn": "Sulfur",
    "formula": "S",
    "cas": "7704-34-9",
    "un": "1350",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים דליקים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "נפטלין",
    "nameEn": "Naphthalene",
    "formula": "C₁₀H₈",
    "cas": "91-20-3",
    "un": "1334",
    "dot": "",
    "fp": "79",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים בעירים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "2",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "פרדיכלורובנזן",
    "nameEn": "p-Dichlorobenzene",
    "formula": "C₆H₄Cl₂",
    "cas": "106-46-7",
    "un": "1592",
    "dot": "",
    "fp": "66",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים בעירים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "2",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "יוד",
    "nameEn": "Iodine",
    "formula": "I₂",
    "cas": "7553-56-2",
    "un": "3495",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-ox",
    "note": ""
  },
  {
    "nameHe": "ברום",
    "nameEn": "Bromine",
    "formula": "Br₂",
    "cas": "7726-95-6",
    "un": "1744",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-ox",
    "note": ""
  },
  {
    "nameHe": "פנול",
    "nameEn": "Phenol",
    "formula": "C₆H₅OH",
    "cas": "108-95-2",
    "un": "1671",
    "dot": "",
    "fp": "79",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "2",
    "r": "0",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "אנילין",
    "nameEn": "Aniline",
    "formula": "C₆H₅NH₂",
    "cas": "62-53-3",
    "un": "1547",
    "dot": "",
    "fp": "70",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "2",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "אקרילוניטריל",
    "nameEn": "Acrylonitrile",
    "formula": "C₃H₃N",
    "cas": "107-13-1",
    "un": "1093",
    "dot": "",
    "fp": "0",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים דליקים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "3",
    "r": "2",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "אתילן אוקסיד",
    "nameEn": "Ethylene Oxide",
    "formula": "C₂H₄O",
    "cas": "75-21-8",
    "un": "1040",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים דליקים רעילים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "4",
    "r": "3",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "אקרולאין",
    "nameEn": "Acrolein",
    "formula": "C₃H₄O",
    "cas": "107-02-8",
    "un": "1092",
    "dot": "",
    "fp": "-26",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים דליקים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "3",
    "r": "3",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "הידרזין",
    "nameEn": "Hydrazine",
    "formula": "N₂H₄",
    "cas": "302-01-2",
    "un": "2029",
    "dot": "",
    "fp": "38",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים דליקים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "3",
    "r": "3",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "ניטרובנזן",
    "nameEn": "Nitrobenzene",
    "formula": "C₆H₅NO₂",
    "cas": "98-95-3",
    "un": "1662",
    "dot": "",
    "fp": "88",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "2",
    "r": "1",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Mercury Fulminate",
    "nameEn": "Hg(CNO)2",
    "formula": "Hg(CNO)₂",
    "cas": "628-86-4",
    "un": "0135",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרי נפץ",
    "cat": "Unstable (Reactive)",
    "cls": "4",
    "clsLbl": "לא יציב 4",
    "cat2": "",
    "h": "3",
    "f": "4",
    "r": "4",
    "sp": "",
    "cc": "nc-unst",
    "note": ""
  },
  {
    "nameHe": "Hydrazoic Acid",
    "nameEn": "HN3",
    "formula": "HN₃",
    "cas": "7782-79-8",
    "un": "",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים לא יציבים",
    "cat": "Unstable (Reactive)",
    "cls": "3",
    "clsLbl": "לא יציב 3",
    "cat2": "",
    "h": "4",
    "f": "2",
    "r": "4",
    "sp": "",
    "cc": "nc-unst",
    "note": ""
  },
  {
    "nameHe": "Potassium Permanganate",
    "nameEn": "KMnO4",
    "formula": "KMnO₄",
    "cas": "7722-64-7",
    "un": "1490",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox2",
    "note": ""
  },
  {
    "nameHe": "Potassium Dichromate",
    "nameEn": "K2Cr2O7",
    "formula": "K₂Cr₂O₇",
    "cas": "7778-50-9",
    "un": "3288",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים רעילים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox2",
    "note": ""
  },
  {
    "nameHe": "Potassium Chlorate",
    "nameEn": "KClO3",
    "formula": "KClO₃",
    "cas": "3811-04-9",
    "un": "1485",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox2",
    "note": ""
  },
  {
    "nameHe": "Sodium Chlorate",
    "nameEn": "NaClO3",
    "formula": "NaClO₃",
    "cas": "7775-09-9",
    "un": "1495",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox2",
    "note": ""
  },
  {
    "nameHe": "Calcium Hypochlorite",
    "nameEn": "Ca(ClO)2",
    "formula": "Ca(ClO)₂",
    "cas": "7778-54-3",
    "un": "1748",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox2",
    "note": ""
  },
  {
    "nameHe": "Chromic Acid",
    "nameEn": "H2CrO4",
    "formula": "H₂CrO₄",
    "cas": "7738-94-5",
    "un": "1463",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים רעילים",
    "cat": "Oxidizer",
    "cls": "3",
    "clsLbl": "סיווג 3",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-ox3",
    "note": ""
  },
  {
    "nameHe": "Nitric Acid Fuming",
    "nameEn": "Red Fuming HNO3",
    "formula": "HNO₃",
    "cas": "7697-37-2",
    "un": "2032",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים רעילים",
    "cat": "Oxidizer",
    "cls": "4",
    "clsLbl": "סיווג 4",
    "cat2": "",
    "h": "4",
    "f": "0",
    "r": "2",
    "sp": "",
    "cc": "nc-ox4",
    "note": ""
  },
  {
    "nameHe": "Sodium Peroxide",
    "nameEn": "Na2O2",
    "formula": "Na₂O₂",
    "cas": "1313-60-6",
    "un": "1504",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "2",
    "sp": "",
    "cc": "nc-ox2",
    "note": ""
  },
  {
    "nameHe": "Potassium Perchlorate",
    "nameEn": "KClO4",
    "formula": "KClO₄",
    "cas": "7778-74-7",
    "un": "1489",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "",
    "h": "1",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox2",
    "note": ""
  },
  {
    "nameHe": "Barium Peroxide",
    "nameEn": "BaO2",
    "formula": "BaO₂",
    "cas": "1304-29-6",
    "un": "1449",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "2",
    "clsLbl": "סיווג 2",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox2",
    "note": ""
  },
  {
    "nameHe": "Magnesium Perchlorate",
    "nameEn": "Mg(ClO4)2",
    "formula": "Mg(ClO₄)₂",
    "cas": "10034-81-8",
    "un": "1475",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "1",
    "clsLbl": "סיווג 1",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox1",
    "note": ""
  },
  {
    "nameHe": "Peracetic Acid 40%",
    "nameEn": "PAA",
    "formula": "C₂H₄O₃",
    "cas": "79-21-0",
    "un": "2131",
    "dot": "",
    "fp": "41",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פרוקסידים אורגניים",
    "cat": "Organic Peroxide",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "2",
    "r": "4",
    "sp": "",
    "cc": "nc-op",
    "note": ""
  },
  {
    "nameHe": "Chlorine Pentafluoride",
    "nameEn": "ClF5",
    "formula": "ClF₅",
    "cas": "13637-63-3",
    "un": "2548",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים מחמצנים",
    "cat": "Oxidizing Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "0",
    "r": "4",
    "sp": "",
    "cc": "nc-oxgas",
    "note": ""
  },
  {
    "nameHe": "Ozone",
    "nameEn": "O3",
    "formula": "O₃",
    "cas": "10028-15-6",
    "un": "",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים מחמצנים רעילים",
    "cat": "Oxidizing Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "4",
    "sp": "",
    "cc": "nc-oxgas",
    "note": ""
  },
  {
    "nameHe": "Perchloryl Fluoride",
    "nameEn": "ClO3F",
    "formula": "ClO₃F",
    "cas": "7616-94-6",
    "un": "3083",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים מחמצנים",
    "cat": "Oxidizing Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "3",
    "sp": "",
    "cc": "nc-oxgas",
    "note": ""
  },
  {
    "nameHe": "Benzidine",
    "nameEn": "4,4'-Diaminobiphenyl",
    "formula": "C₁₂H₁₂N₂",
    "cas": "92-87-5",
    "un": "1885",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים מסרטנים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Vinyl Chloride",
    "nameEn": "Chloroethylene",
    "formula": "C₂H₃Cl",
    "cas": "75-01-4",
    "un": "1086",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים מסרטנים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "1,3-Butadiene",
    "nameEn": "Divinyl",
    "formula": "C₄H₆",
    "cas": "106-99-0",
    "un": "1010",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים מסרטנים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "Ethylene Dibromide",
    "nameEn": "EDB",
    "formula": "C₂H₄Br₂",
    "cas": "106-93-4",
    "un": "1605",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים מסרטנים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Ethylene Dichloride",
    "nameEn": "EDC",
    "formula": "C₂H₄Cl₂",
    "cas": "107-06-2",
    "un": "1184",
    "dot": "",
    "fp": "13",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים מסרטנים דליקים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "3",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Bis(chloromethyl)ether",
    "nameEn": "BCME",
    "formula": "C₂H₄Cl₂O",
    "cas": "542-88-1",
    "un": "2249",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים מסרטנים מאוד",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "3",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "beta-Propiolactone",
    "nameEn": "BPL",
    "formula": "C₃H₄O₂",
    "cas": "57-57-8",
    "un": "",
    "dot": "",
    "fp": "75",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים מסרטנים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "2",
    "r": "3",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Hexamethylphosphoramide",
    "nameEn": "HMPA",
    "formula": "C₆H₁₈N₃OP",
    "cas": "680-31-9",
    "un": "",
    "dot": "",
    "fp": "105",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים מסרטנים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "N-Nitrosodimethylamine",
    "nameEn": "NDMA",
    "formula": "C₂H₆N₂O",
    "cas": "62-75-9",
    "un": "",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים מסרטנים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "2",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Aflatoxin B1",
    "nameEn": "AFB1",
    "formula": "C₁₇H₁₂O₆",
    "cas": "1162-65-8",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים מסרטנים מאוד",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Asbestos",
    "nameEn": "Chrysotile",
    "formula": "Mg₃Si₂O₅(OH)₄",
    "cas": "12001-29-5",
    "un": "2590",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים מסרטנים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Beryllium",
    "nameEn": "Be",
    "formula": "Be",
    "cas": "7440-41-7",
    "un": "1567",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מתכות מסרטנות",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "1",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Cadmium",
    "nameEn": "Cd",
    "formula": "Cd",
    "cas": "7440-43-9",
    "un": "2570",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מתכות רעילות",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Chromium VI",
    "nameEn": "Cr(VI)",
    "formula": "CrO₃",
    "cas": "1333-82-0",
    "un": "1463",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מחמצנים מסרטנים",
    "cat": "Oxidizer",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox",
    "note": ""
  },
  {
    "nameHe": "Nickel Subsulfide",
    "nameEn": "Ni3S2",
    "formula": "Ni₃S₂",
    "cas": "12035-72-2",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים מסרטנים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Ammonia-d3",
    "nameEn": "Deuterated Ammonia",
    "formula": "ND₃",
    "cas": "13550-49-7",
    "un": "",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Boron Trichloride",
    "nameEn": "BCl3",
    "formula": "BCl₃",
    "cas": "10294-34-5",
    "un": "1741",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "2",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "Boron Trifluoride",
    "nameEn": "BF3",
    "formula": "BF₃",
    "cas": "7637-07-2",
    "un": "1008",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "Silicon Tetrachloride",
    "nameEn": "SiCl4",
    "formula": "SiCl₄",
    "cas": "10026-04-7",
    "un": "1818",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "2",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "Titanium Tetrachloride",
    "nameEn": "TiCl4",
    "formula": "TiCl₄",
    "cas": "7550-45-0",
    "un": "1838",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "2",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "Tungsten Hexafluoride",
    "nameEn": "WF6",
    "formula": "WF₆",
    "cas": "7783-82-6",
    "un": "2196",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "2",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "Nitrous Oxide",
    "nameEn": "N2O",
    "formula": "N₂O",
    "cas": "10024-97-2",
    "un": "1070",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים מחמצנים",
    "cat": "Oxidizing Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "0",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-oxgas",
    "note": ""
  },
  {
    "nameHe": "Liquid Natural Gas",
    "nameEn": "LNG",
    "formula": "CH₄",
    "cas": "74-82-8",
    "un": "1972",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים דליקים קריוגניים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "Liquid Petroleum Gas",
    "nameEn": "LPG",
    "formula": "C₃H₈/C₄H₁₀",
    "cas": "68476-85-7",
    "un": "1075",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "Compressed Natural Gas",
    "nameEn": "CNG",
    "formula": "CH₄",
    "cas": "74-82-8",
    "un": "1971",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "HMPA",
    "nameEn": "Hexamethylphosphoramide",
    "formula": "C₆H₁₈N₃OP",
    "cas": "680-31-9",
    "un": "",
    "dot": "",
    "fp": "105",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים דליקים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Benzene-d6",
    "nameEn": "Deuterated Benzene",
    "formula": "C₆D₆",
    "cas": "1076-43-3",
    "un": "",
    "dot": "",
    "fp": "-11",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "ממסי NMR דליקים",
    "cat": "Flammable Liquid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "3",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "Toluene-d8",
    "nameEn": "Deuterated Toluene",
    "formula": "C₇D₈",
    "cas": "2037-26-5",
    "un": "",
    "dot": "",
    "fp": "4",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "ממסי NMR דליקים",
    "cat": "Flammable Liquid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "3",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "Acetone-d6",
    "nameEn": "Deuterated Acetone",
    "formula": "C₃D₆O",
    "cas": "666-52-4",
    "un": "",
    "dot": "",
    "fp": "-18",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "ממסי NMR דליקים",
    "cat": "Flammable Liquid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "3",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "Methanol-d4",
    "nameEn": "Deuterated Methanol",
    "formula": "CD₃OD",
    "cas": "811-98-3",
    "un": "",
    "dot": "",
    "fp": "11",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "ממסי NMR דליקים",
    "cat": "Flammable Liquid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "3",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "Grignard Reagent",
    "nameEn": "Methylmagnesium Chloride",
    "formula": "CH₃MgCl",
    "cas": "676-58-4",
    "un": "3399",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "3",
    "r": "3",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "LDA",
    "nameEn": "Lithium Diisopropylamide",
    "formula": "C₆H₁₄LiN",
    "cas": "4111-54-0",
    "un": "",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "בסיסים חזקים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "3",
    "r": "3",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "LHMDS",
    "nameEn": "Lithium Hexamethyldisilazide",
    "formula": "C₆H₁₈LiNSi₂",
    "cas": "4039-32-1",
    "un": "",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "בסיסים חזקים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "2",
    "r": "3",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "DIBAL-H",
    "nameEn": "Diisobutylaluminum Hydride",
    "formula": "C₈H₁₉Al",
    "cas": "1191-15-7",
    "un": "3394",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "4",
    "r": "3",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Red-Al",
    "nameEn": "Sodium Bis(2-methoxyethoxy)aluminum Hydride",
    "formula": "C₆H₁₆AlNaO₄",
    "cas": "22722-98-1",
    "un": "",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "2",
    "r": "3",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "LAH",
    "nameEn": "Lithium Aluminum Hydride",
    "formula": "LiAlH₄",
    "cas": "16853-85-3",
    "un": "1410",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "2",
    "r": "3",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "NaBH4",
    "nameEn": "Sodium Borohydride",
    "formula": "NaBH₄",
    "cas": "16940-66-2",
    "un": "1426",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "1",
    "r": "3",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "LiBH4",
    "nameEn": "Lithium Borohydride",
    "formula": "LiBH₄",
    "cas": "16949-15-8",
    "un": "1413",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "2",
    "r": "3",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "HMTA",
    "nameEn": "Hexamethylenetetramine",
    "formula": "C₆H₁₂N₄",
    "cas": "100-97-0",
    "un": "1328",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מוצקים דליקים",
    "cat": "Flammable Solid",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "Oxalyl Chloride",
    "nameEn": "COCl-COCl",
    "formula": "C₂Cl₂O₂",
    "cas": "79-37-8",
    "un": "2046",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "2",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "Thionyl Chloride",
    "nameEn": "SOCl2",
    "formula": "SOCl₂",
    "cas": "7719-09-7",
    "un": "1836",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "2",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "Phosphorus Pentoxide",
    "nameEn": "P2O5",
    "formula": "P₂O₅",
    "cas": "1314-56-3",
    "un": "1807",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "2",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "Phosphorus Trichloride",
    "nameEn": "PCl3",
    "formula": "PCl₃",
    "cas": "7719-12-2",
    "un": "1809",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "2",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "Phosphorus Pentachloride",
    "nameEn": "PCl5",
    "formula": "PCl₅",
    "cas": "10026-13-8",
    "un": "1806",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "2",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "Phosphorus Oxychloride",
    "nameEn": "POCl3",
    "formula": "POCl₃",
    "cas": "10025-87-3",
    "un": "1810",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים קורוזיביים",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "2",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "Trifluoroacetic Acid",
    "nameEn": "TFA",
    "formula": "C₂HF₃O₂",
    "cas": "76-05-1",
    "un": "2699",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומצות קורוזיביות",
    "cat": "Corrosive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-corr",
    "note": ""
  },
  {
    "nameHe": "Palladium on Carbon",
    "nameEn": "Pd/C",
    "formula": "Pd",
    "cas": "7440-05-3",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Platinum on Carbon",
    "nameEn": "Pt/C",
    "formula": "Pt",
    "cas": "7440-06-4",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Raney Nickel",
    "nameEn": "Ni-Al",
    "formula": "Ni",
    "cas": "7440-02-0",
    "un": "1378",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Rhodium on Alumina",
    "nameEn": "Rh/Al2O3",
    "formula": "Rh",
    "cas": "7440-16-6",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "קטליזטורים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Ruthenium on Carbon",
    "nameEn": "Ru/C",
    "formula": "Ru",
    "cas": "7440-18-8",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Wilkinson's Catalyst",
    "nameEn": "RhCl(PPh3)3",
    "formula": "C₅₄H₄₅ClP₃Rh",
    "cas": "14694-95-2",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "קטליזטורים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Grubbs Catalyst",
    "nameEn": "Ru Metathesis",
    "formula": "C₄₆H₆₅Cl₂NP₂Ru",
    "cas": "172222-30-9",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "קטליזטורים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Crabtree's Catalyst",
    "nameEn": "Ir Complex",
    "formula": "C₂₄H₃₆ClIrN₂O₈S₂",
    "cas": "64536-78-3",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "קטליזטורים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Lindlar Catalyst",
    "nameEn": "Pd-CaCO3-Pb",
    "formula": "Pd",
    "cas": "",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "קטליזטורים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "2",
    "r": "1",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Adam's Catalyst",
    "nameEn": "PtO2",
    "formula": "PtO₂",
    "cas": "1314-15-4",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "קטליזטורים מחמצנים",
    "cat": "Oxidizer",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox",
    "note": ""
  },
  {
    "nameHe": "Copper Chromite",
    "nameEn": "Cu-Cr2O3",
    "formula": "CuCr₂O₄",
    "cas": "12018-10-9",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "קטליזטורים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Nickel Boride",
    "nameEn": "Ni2B",
    "formula": "Ni₂B",
    "cas": "12007-00-0",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "3",
    "r": "2",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Cobalt on Carbon",
    "nameEn": "Co/C",
    "formula": "Co",
    "cas": "7440-48-4",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "3",
    "r": "2",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Silver Oxide",
    "nameEn": "Ag2O",
    "formula": "Ag₂O",
    "cas": "20667-12-3",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מחמצנים",
    "cat": "Oxidizer",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox",
    "note": ""
  },
  {
    "nameHe": "Manganese Dioxide",
    "nameEn": "MnO2",
    "formula": "MnO₂",
    "cas": "1313-13-9",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "מחמצנים",
    "cat": "Oxidizer",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "1",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-ox",
    "note": ""
  },
  {
    "nameHe": "Malathion",
    "nameEn": "Insecticide",
    "formula": "C₁₀H₁₉O₆PS₂",
    "cas": "121-75-5",
    "un": "2783",
    "dot": "",
    "fp": "163",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Paraquat",
    "nameEn": "Herbicide",
    "formula": "C₁₂H₁₄Cl₂N₂",
    "cas": "4685-14-7",
    "un": "2781",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים מאוד",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Glyphosate",
    "nameEn": "Roundup",
    "formula": "C₃H₈NO₅P",
    "cas": "1071-83-6",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "DDT",
    "nameEn": "Dichlorodiphenyltrichloroethane",
    "formula": "C₁₄H₉Cl₅",
    "cas": "50-29-3",
    "un": "2761",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Carbaryl",
    "nameEn": "Sevin",
    "formula": "C₁₂H₁₁NO₂",
    "cas": "63-25-2",
    "un": "2757",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Atrazine",
    "nameEn": "Herbicide",
    "formula": "C₈H₁₄ClN₅",
    "cas": "1912-24-9",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Chlorpyrifos",
    "nameEn": "Insecticide",
    "formula": "C₉H₁₁Cl₃NO₃PS",
    "cas": "2921-88-2",
    "un": "2783",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Permethrin",
    "nameEn": "Insecticide",
    "formula": "C₂₁H₂₀Cl₂O₃",
    "cas": "52645-53-1",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Methyl Bromide",
    "nameEn": "Fumigant",
    "formula": "CH₃Br",
    "cas": "74-83-9",
    "un": "1062",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Phosphine",
    "nameEn": "Fumigant",
    "formula": "PH₃",
    "cas": "7803-51-2",
    "un": "2199",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Aluminum Phosphide",
    "nameEn": "Fumigant",
    "formula": "AlP",
    "cas": "20859-73-8",
    "un": "1397",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רגישים למים",
    "cat": "Water-Reactive",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "2",
    "r": "3",
    "sp": "",
    "cc": "nc-wat",
    "note": ""
  },
  {
    "nameHe": "Warfarin",
    "nameEn": "Rodenticide",
    "formula": "C₁₉H₁₆O₄",
    "cas": "81-81-2",
    "un": "3027",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Strychnine",
    "nameEn": "Pesticide",
    "formula": "C₂₁H₂₂N₂O₂",
    "cas": "57-24-9",
    "un": "1692",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים מאוד",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Rotenone",
    "nameEn": "Insecticide",
    "formula": "C₂₃H₂₂O₆",
    "cas": "83-79-4",
    "un": "",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Nicotine",
    "nameEn": "Insecticide",
    "formula": "C₁₀H₁₄N₂",
    "cas": "54-11-5",
    "un": "1654",
    "dot": "",
    "fp": "95",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים מאוד",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "1",
    "r": "0",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "בנזואיל פרוקסיד",
    "nameEn": "Benzoyl Peroxide",
    "formula": "C₁₄H₁₀O₄",
    "cas": "94-36-0",
    "un": "2085",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פרוקסידים אורגניים",
    "cat": "Organic Peroxide",
    "cls": "IIA",
    "clsLbl": "סיווג IIA",
    "cat2": "",
    "h": "1",
    "f": "4",
    "r": "4",
    "sp": "",
    "cc": "nc-op2a",
    "note": ""
  },
  {
    "nameHe": "MEKP",
    "nameEn": "Methyl Ethyl Ketone Peroxide",
    "formula": "C₈H₁₈O₆",
    "cas": "1338-23-4",
    "un": "2550",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פרוקסידים אורגניים",
    "cat": "Organic Peroxide",
    "cls": "I",
    "clsLbl": "סיווג I",
    "cat2": "",
    "h": "3",
    "f": "4",
    "r": "4",
    "sp": "",
    "cc": "nc-op1",
    "note": ""
  },
  {
    "nameHe": "Di-tert-butyl Peroxide",
    "nameEn": "DTBP",
    "formula": "C₈H₁₈O₂",
    "cas": "110-05-4",
    "un": "2102",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פרוקסידים אורגניים",
    "cat": "Organic Peroxide",
    "cls": "IIB",
    "clsLbl": "סיווג IIB",
    "cat2": "",
    "h": "2",
    "f": "4",
    "r": "4",
    "sp": "",
    "cc": "nc-op2b",
    "note": ""
  },
  {
    "nameHe": "Peracetic Acid",
    "nameEn": "Peroxyacetic Acid",
    "formula": "C₂H₄O₃",
    "cas": "79-21-0",
    "un": "2131",
    "dot": "",
    "fp": "41",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "פרוקסידים אורגניים",
    "cat": "Organic Peroxide",
    "cls": "III",
    "clsLbl": "סיווג III",
    "cat2": "",
    "h": "3",
    "f": "2",
    "r": "4",
    "sp": "",
    "cc": "nc-op3",
    "note": ""
  },
  {
    "nameHe": "Trimethylaluminum",
    "nameEn": "TMA",
    "formula": "Al(CH₃)₃",
    "cas": "75-24-1",
    "un": "3051",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "4",
    "r": "3",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "n-Butyllithium",
    "nameEn": "BuLi",
    "formula": "C₄H₉Li",
    "cas": "109-72-8",
    "un": "2445",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "3",
    "f": "4",
    "r": "3",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Silane",
    "nameEn": "Silicon Tetrahydride",
    "formula": "SiH₄",
    "cas": "7803-62-5",
    "un": "2203",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים פירוטכניים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "2",
    "f": "4",
    "r": "3",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "Phosphine",
    "nameEn": "PH3",
    "formula": "PH₃",
    "cas": "7803-51-2",
    "un": "2199",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים פירוטכניים רעילים",
    "cat": "Pyrophoric",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-pyr",
    "note": ""
  },
  {
    "nameHe": "פוסגן",
    "nameEn": "Phosgene",
    "formula": "COCl₂",
    "cas": "75-44-5",
    "un": "1076",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים מאוד",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "0",
    "r": "1",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Hydrogen Sulfide",
    "nameEn": "H2S",
    "formula": "H₂S",
    "cas": "7783-06-4",
    "un": "1053",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "4",
    "r": "0",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "Arsine",
    "nameEn": "AsH3",
    "formula": "AsH₃",
    "cas": "7784-42-1",
    "un": "2188",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים מאוד",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Fluorine",
    "nameEn": "F2",
    "formula": "F₂",
    "cas": "7782-41-4",
    "un": "1045",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים מחמצנים רעילים",
    "cat": "Oxidizing Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "0",
    "r": "4",
    "sp": "",
    "cc": "nc-oxgas",
    "note": ""
  },
  {
    "nameHe": "Hydrogen Cyanide",
    "nameEn": "HCN",
    "formula": "HCN",
    "cas": "74-90-8",
    "un": "1051",
    "dot": "",
    "fp": "גז",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "גזים רעילים מאוד דליקים",
    "cat": "Flammable Gas",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "4",
    "r": "2",
    "sp": "",
    "cc": "nc-flam",
    "note": ""
  },
  {
    "nameHe": "Dimethyl Sulfate",
    "nameEn": "DMS",
    "formula": "C₂H₆O₄S",
    "cas": "77-78-1",
    "un": "1595",
    "dot": "",
    "fp": "83",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים רעילים מאוד",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "1",
    "r": "2",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Methyl Isocyanate",
    "nameEn": "MIC",
    "formula": "C₂H₃NO",
    "cas": "624-83-9",
    "un": "2480",
    "dot": "",
    "fp": "-7",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "נוזלים רעילים מאוד דליקים",
    "cat": "Toxic",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "3",
    "r": "3",
    "sp": "",
    "cc": "nc-tox",
    "note": ""
  },
  {
    "nameHe": "Nitroglycerin",
    "nameEn": "NG",
    "formula": "C₃H₅N₃O₉",
    "cas": "55-63-0",
    "un": "0143",
    "dot": "",
    "fp": "נוזל",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים לא יציבים",
    "cat": "Unstable (Reactive)",
    "cls": "4",
    "clsLbl": "לא יציב 4",
    "cat2": "",
    "h": "2",
    "f": "4",
    "r": "4",
    "sp": "",
    "cc": "nc-unst",
    "note": ""
  },
  {
    "nameHe": "RDX",
    "nameEn": "Cyclonite",
    "formula": "C₃H₆N₆O₆",
    "cas": "121-82-4",
    "un": "0072",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרי נפץ",
    "cat": "Unstable (Reactive)",
    "cls": "4",
    "clsLbl": "לא יציב 4",
    "cat2": "",
    "h": "2",
    "f": "4",
    "r": "4",
    "sp": "",
    "cc": "nc-unst",
    "note": ""
  },
  {
    "nameHe": "Picric Acid",
    "nameEn": "TNP",
    "formula": "C₆H₃N₃O₇",
    "cas": "88-89-1",
    "un": "0154",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרי נפץ",
    "cat": "Unstable (Reactive)",
    "cls": "3",
    "clsLbl": "לא יציב 3",
    "cat2": "",
    "h": "3",
    "f": "4",
    "r": "4",
    "sp": "",
    "cc": "nc-unst",
    "note": ""
  },
  {
    "nameHe": "Ammonium Perchlorate",
    "nameEn": "AP",
    "formula": "NH₄ClO₄",
    "cas": "7790-98-9",
    "un": "1442",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "חומרים מחמצנים",
    "cat": "Oxidizer",
    "cls": "4",
    "clsLbl": "סיווג 4",
    "cat2": "",
    "h": "2",
    "f": "0",
    "r": "4",
    "sp": "",
    "cc": "nc-ox4",
    "note": ""
  },
  {
    "nameHe": "Sodium Azide",
    "nameEn": "NaN3",
    "formula": "NaN₃",
    "cas": "26628-22-8",
    "un": "1687",
    "dot": "",
    "fp": "מוצק",
    "bp": "",
    "lel": "",
    "uel": "",
    "ait": "",
    "catHe": "רעילים לא יציבים",
    "cat": "Unstable (Reactive)",
    "cls": "",
    "clsLbl": "",
    "cat2": "",
    "h": "4",
    "f": "1",
    "r": "3",
    "sp": "",
    "cc": "nc-unst",
    "note": ""
  }
];
